const pileTypes = {
    DUTCH_PILE: 'DUTCH_PILE',
    WOOD_PILE: 'WOOD_PILE',
    LEFT_POST_PILE: 'LEFT_POST_PILE',
    MIDDLE_POST_PILE: 'MIDDLE_POST_PILE',
    RIGHT_POST_PILE: 'RIGHT_POST_PILE',
    BLITZ_PILE: 'BLITZ_PILE'
};

export default pileTypes;